spring.application.name=ecommercespring
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=User1573

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true